### ISSUE TITLE
PJLink and freeze function issue

### ISSUE THREAD

**Issue by JWBogers** [bitfocus/companion-module-pjlink#1]
I'm trying to get the freeze function working on a Panasonic DZ13KE and a couple of Panasonic DX500E's and tried a couple of things but none of them are working. All other commands are working fine. Does anyone else have the same problem?

**Comment by krocheck** [comment]
I could be wrong, but I don't think Panasonic projectors have/support the 'freeze' function.  To be clear, you want to take the picture that's on screen from a source and, effectively, pause it?

**Comment by krocheck** [comment]
So I pulled the DZ13KE manual.  Its lists the following as supported Pjlink commands:
- POWR / POWR? (power)
- INPT / INPT? (input)
- AVMT / AVMT? (shutter)
- ERST? (error status)
- LAMP? (lamp hours)
- INST? (list available inputs)
- NAME? (projector name)
- INF1? (manufacturer)
- INF2? (model)
- INF0? (version)
- CLSS? (pjlink version)

No freeze exposed per the manual.

**Comment by JeffreyDavidsz** [comment]
Freeze not supported for this type projector
