### ISSUE TITLE
pjlink power state feedback

### ISSUE THREAD

**Issue by G-Hansen** [bitfocus/companion-module-pjlink#12]
Is it possible to add a feedback that would change the background color depending on the power state of the projector?

**Comment by oschuetze** [comment]
According to the [specification](https://pjlink.jbmia.or.jp/english/data_cl2/PJLink_5-1.pdf), there is a "Power status query POWR ?"

**Comment by deewhitewolf** [comment]
This would be useful to have. Wouldn't be that hard to implement I would have thought

**Comment by mabyoro** [comment]
I highly recommend this request! at least power and shutter-status is needed.
