### ISSUE TITLE
Hitachi Projector PJLink not working

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-pjlink#14]
Hi, 
I have a Hitachi Projector that does not respond with this module, I have tested using the PJlink tester from the PJlink website and all works correctly. I have noticed in the logs that the test software shows "RECV:%1POWR 0" and the companion module shows "RECV:%1powr 0". Does the message all need to be in Capitals to function ?

Many Thanks

Jonathan

**Comment by istnv** [comment]
The PJLINK specifications state that the command 'word' is case-insensitive so it shouldn't matter. The module sends lower case for all commands, and works fine with my NEC projector. 
There have been other comments about the module not working on some models. 
So I think there may be certain (incomplete) manufacturer implementations that don't respond to lower-case. 
Maybe the module should send upper case commands.

**Comment by Jonhug82** [comment]
I have modified the module running on my system to now send commands using capital letters and the projector is responding perfectly. A shame manufacturers can't stick to the specifications!

**Comment by jmcc94** [comment]
Closing as issue seems to be resolved with last comment
