### ISSUE TITLE
Epson EB-L510U

### ISSUE THREAD

**Issue by MCE2021-ui** [bitfocus/companion-module-pjlink#19]
Hi there,

newbie here - I managed to connect our Epson EB-L510U via LAN and can "power off" the device. However, I cannot "Power On". Is this a setting in the beamer to wait for Power on LAN or what do I need to do?

Thanks so much for your help!

**Comment by JerryLathem** [comment]
Make sure in your configuration on the Epson that Standby Mode is set to "Communications On"
<img width="787" alt="Screen Shot 2022-02-01 at 12 28 36 PM" src="https://user-images.githubusercontent.com/48189854/152028625-43376144-b33c-490f-8343-91b09ee0639b.png">

**Comment by jmcc94** [comment]
Closing as seems to be resolved
