### ISSUE TITLE
pjlink Feedback

### ISSUE THREAD

**Issue by PixelWorld1234** [bitfocus/companion-module-pjlink#20]
Hi. Can we have a feedback from the pjlink? 
Just to know basis command like power or shuttle in on/off,

Not sure this file will help it?
[PJLink_5-1.pdf](https://github.com/bitfocus/companion-module-requests/files/7313415/PJLink_5-1.pdf)

**Comment by josephdadams** [comment]
Transferring this to the pjlink module repo and someone can deal with it there

**Comment by mabyoro** [comment]
I highly recommend this request! at least power and shutter-status is needed.

**Comment by AlainCx** [comment]
Idem, and with lamp hours feedback too

**Comment by istnv** [comment]
Have you looked at the docs?
Note: Lamp hours does not exist on laser projectors

```
**Available variables for PJLink**

Projector Class
Projector Name
Projector Manufacturer
Projector Product Name
Projector Other Info
Error Status
Freeze Status
Input Horizontal Resolution
Input Vertical Resolution
Recommended Horizontal Resolution
Recommended Vertical Resolution
Lamp Hour (Lamps 1 to 8)
Lamp On (Lamps 1 to 8)
Serial Number
Software Version
Filter Usage Time
Filter Replacement Model Number
Lamp Replacement Model Number
Mute Status
Power Status
Projector Input

**Available feedback for PJLink**

Error Status
Freeze Status
Lamp Hour
Mute Status
Power Status
Projector Input`

**Comment by mabyoro** [comment]
our Laser-Projectors (Panasonic PT-RZ31, RZ970 and RZ120) all do have Lamp Hour-Feedback.

**Comment by istnv** [comment]
That's interesting. The Panasonic PT-RZ470U definitely returns an error when querying lamp hours. (See issue #45)
The module only disables the query when receiving an error. 
> our Laser-Projectors (Panasonic PT-RZ31, RZ970 and RZ120) all do have Lamp Hour-Feedback.
