### ISSUE TITLE
FEATURE REQUEST:  Lens Shift Functions

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-pjlink#38]
Not sure how to read the API docs to see if this is possible.  Would love to be able to control the lens shift functions on the  Epson L1500U.  It is controllable from the webGUI so would think there is a method there.  

This link has some docs including an ART NET command list if that is helpful.  I need to get schooled on these things so I can be more help!

https://epson.com/Support/Projectors/Pro-Series/Epson-Pro-L1500UH/s/SPT_V11H910020 

Thanks!

**Comment by istnv** [comment]
Can't be done with the PJLink protocol. Try the Epson specific module `epson-businesspj`
