### ISSUE TITLE
Change Projector Power State issue with Toggle option

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-pjlink#39]
Button assigned with Projector Power State to **Toggle** doesn't work.

Companion Build: [2.3.0 (2.3.0+4547-beta-a8f59e4e)]
Projector Model: EPSON L615U/L610U

Error Message:
`22.07.20 16:36:01 instance(pjlink): Projector reported %1POWR: Out of parameter`

Working fine when the button is set to **On** or **Off**.

Would like to get the Toggle feature working. Thanks.

**Comment by istnv** [comment]
I did not actually implement this particular feature because it would be way too easy to power off the projector.

**Comment by tpk001** [comment]
It would be good if we can have it as we can keep one button to do the On/Off than creating 2 buttons.
Any possibility of adding it in?

**Comment by jmcc94** [comment]
@tpk001 - While waiting for the functionality to be added to the module, you could create a toggle button in companion...

Latch down with the Power On action, and unlatch with the Power Off action

**Comment by tpk001** [comment]
@jmcc94 I know but it will be incorrect when someone turns on/off the projector using a remote. 
e.g.- Button will be latched even though the projector is Off.

**Comment by tpk001** [comment]
Thanks
