### ISSUE TITLE
Power on for Epson Pro 1500U is hit or miss. 

### ISSUE THREAD

**Issue by roshjothe** [bitfocus/companion-module-pjlink#41]
Whenever I attempt to turn on my epson projector, maybe one out of every 5 presses sends the power on signal to the projector. Turning off is no issue at all, and the projector consistently turns off whenever the command is sent. It flashes multiple error codes in the companion logs. Sometimes it's %1AVMT, %2INPT, or %2RLMP. I've tried to adjust the polling time to multiple different times, but nothing seems to work. My sony projectors have no issue at all powering on or off, so this might be specific to this projector. 

![Screen Shot 2022-07-28 at 4 40 44 PM](https://user-images.githubusercontent.com/108298706/181642385-da27dae9-4fc9-4b56-9706-8e90fae6df5f.png)

**Comment by istnv** [comment]
Which companion build/version are you using?
'Unavailable time' is a projector busy signal. It is warming up, waking up, in-between inputs (new input has not been synced) 
The error on the %2RLMP means the projector uses version 1 and does not understand the command.
The latest updates have a lot of checks to prevent sending commands that could cause errors.

**Comment by roshjothe** [comment]
I'm currently using companion 2.2.3

**Comment by roshjothe** [comment]
Do you think I should download a prior build then?

**Comment by istnv** [comment]
No. Prior builds are worse. What is the build #? 
![image](https://user-images.githubusercontent.com/51003420/181645305-1ae9dda1-abf2-429c-83c7-1b5239d0da4e.png)

**Comment by roshjothe** [comment]
![Screen Shot 2022-07-28 at 5 08 38 PM](https://user-images.githubusercontent.com/108298706/181645735-dd1b3fd4-ed88-4c30-8751-7064690b2d3f.png)

Here's the build number

**Comment by roshjothe** [comment]
Epson webremote is consistent when powering on from the app. I'm not sure if that information is relevant, just though I'd pass that on.

**Comment by istnv** [comment]
The updates are in the beta releases. Currently at 2.3.0+4569.
There are a lot of fixes since the 2.2.3 release.

**Comment by roshjothe** [comment]
Updated and It works! Thank you very much for your help!
