### ISSUE TITLE
Power control doesn't work on NEC P502HL

### ISSUE THREAD

**Issue by rhorer** [bitfocus/companion-module-pjlink#42]
When I try to turn the power on or off with a NEC P502HL projector using the PJLink module, nothing appears to happen. The state of the projector doesn't change and I don't see any attempt in the debug log to even talk to the projector. The connection is good (status is "OK" and the power state feedback on the buttons is accurate) but the power state doesn't change. One time when I hit the power on button a bunch of times in very rapid succession, I got the following entry in Companion's log: "Projector reported Unavailable time. Command was %1POWR".

I can telnet to the projector and issue "%1POWR 1" and "%1POWR 0" and they both work (there is no password set). However, power control through the Companion module does not work.

**Comment by rhorer** [comment]
Other information I should have included… the variables all appear to be correct and current, which again verifies that the connection is working. I didn't notice this before but when the projector is OFF (as opposed to on, shutting down, powering up, etc.) the log periodically (every 40 seconds) issues a warning "instance(foldback): Projector/Display failure".

After more experimentation, it seems that the power control sometimes works and sometimes doesn't. I didn't read issue #41 before because I didn't think the power control was working at all but after experimenting with it more, the problems seem very similar. I may try updating from 2.2.3+4469-v2-2.3-82b174db to the 2.3.0 version mentioned in #41.

**Comment by istnv** [comment]
Power control was a known issue in that release. 2.2.3+4469 is almost 100 builds behind and there was a lot of cleanup for the power states and feedbacks and variables.
Try the developer/beta build mentioned in #41 (2.3.0+4569 or later)

**Comment by sydneyjd** [comment]
I am also having issues getting consistent power on/off results, as well as the freeze command being unreliable, even in the latest beta, as of this writing writing, 2.3.0-4590. Three newer Epson Projectors, One older Epson. Have one button that toggles power to them all(also have tried specific on/off commands, acts the same), and power commands are sporadic. Sometimes when toggling, all three newer ones will work properly, but not the older one, then the next time the newer ones don't respond, and the older one does, and that being with a 1 minute or so delay before hitting the button again.
My error log:
![Screenshot 2022-08-09 173754](https://user-images.githubusercontent.com/8949851/183766848-0d68ee4a-9876-4a40-b354-0dfae7b46b27.png)

**Comment by istnv** [comment]
Hmm. Different class 2 projectors do not support the %@RLMP command. That is a warning that should not affect anything else. The 'Replacement lamp' variable will stay undefined. I am not sure what is happening with the power commands.

**Comment by istnv** [comment]
There have been several recent updates that should correct this. Please re-open if this is still an issue.
