### ISSUE TITLE
Hitachi LP-WU9750B: Most input selections don't work, and the few that do are labeled incorrectly

### ISSUE THREAD

**Issue by isaacclausen** [bitfocus/companion-module-pjlink#44]
This is awesome. I love this tool, thank you for making and maintaining it.
I have a couple Hitachi LP-WU9750B projectors and when I use the PJlink module to change the input, the DVI-D selection changes the projector to HDMI 1, the HDMI selection goes to DVI-D, the Digital Link selection goes to HDMI 2, and the SDI 1 + 2 LAN and HDBaseT do nothing. The RGB 1 and 2 work fine...

<img width="431" alt="Screen Shot 2022-09-21 at 3 14 40 PM" src="https://user-images.githubusercontent.com/83613660/191601568-d627dc60-3c3c-4b25-bfbb-ab89202c88fe.png">
<img width="401" alt="Screen Shot 2022-09-21 at 3 12 31 PM" src="https://user-images.githubusercontent.com/83613660/191601201-30c60ca3-7551-48b8-98bb-4f8c40af8a6a.png">

**Comment by jmcc94** [comment]
Those are the default inputs as per the PJLINK spec, but if your projector can handle Class2 commands, then it should query the projector for the correct input names.

There should be a variable that tells you what class the projector is responding as.

**Comment by isaacclausen** [comment]
The variable is returning 1. Am I missing something?

**Comment by istnv** [comment]
This is a bug. A class 1 projector should update the available inputs to match the projector, even if the names are not available.
Currently, the module does not rebuild the list unless the projector is class 2.
I have noticed that class 1 projectors do not always follow the listed protocol inputs.
