### ISSUE TITLE
Panasonic PT-RZ470U %1LAMP error

### ISSUE THREAD

**Issue by ericbusby77** [bitfocus/companion-module-pjlink#45]
Running v2.3.1+4641, constantly getting the following error in the logs: 
<img width="504" alt="Screen Shot 2022-09-26 at 10 53 14 AM" src="https://user-images.githubusercontent.com/72747174/192324324-721c570a-46d5-427e-868c-9446e797b067.png">
I found this in [the manual](https://na.panasonic.com/ns/9779_PT-RZ470RW430_-_.pdf) for the projector (page 124):
<img width="1115" alt="Screen Shot 2022-09-26 at 10 56 42 AM" src="https://user-images.githubusercontent.com/72747174/192324573-3b1af811-5904-494d-8dc2-3f54daccd9a6.png">

Is this fixable or do we just need to ignore it?

**Comment by istnv** [comment]
The module is asking for lamp hours and the projector is saying no lamps here. 
Which makes sense since that is a laser projector.
You can ignore it.
A upcoming update should filter that from the log as it is not really an error.
