### ISSUE TITLE
Epson PowerLite 99W Authentication Issue

### ISSUE THREAD

**Issue by b-p-michael** [bitfocus/companion-module-pjlink#48]
When using pjlink to connect to an Epson PowerLite 99W authentication fails every other time.  I have tried changing the polling time, and the issue persists.  Web control from the projector works properly.

![pjlink authentication](https://user-images.githubusercontent.com/115583441/195172771-237a5124-6d34-457f-95d7-e69b25821ba8.png)

**Comment by istnv** [comment]
You may need to allow PJLink access (and password) from the Web interface.
