### ISSUE TITLE
Sony projector does not accept password

### ISSUE THREAD

**Issue by peerke444** [bitfocus/companion-module-pjlink#5]
PJlink module loads and connects to our projector but the projector does not accept the password.
Also tried connecting without a password but error message stays the same.

 instance(pjlink): Authentication error. Password not accepted by projector

**Comment by haakonnessjoen** [comment]
Closing this as this seems to have been the issue all along, and it should be working for everyone now.

**Comment by AlainCx** [comment]
Hello,
I discovered Companion few days ago and doing some tests. 
Sony VPL EW295 isn't connecting : it has no password and I have an error in the log : "Authentication error. Password not accepted by projector"
What can I do for solve this ?
