### ISSUE TITLE
Sony projector password 

### ISSUE THREAD

**Issue by AlainCx** [bitfocus/companion-module-pjlink#51]
Hello,
I discovered Companion few days ago and doing some tests. 
Sony VPL EW295 isn't connecting : it has no password and I have an error in the log : "Authentication error. Password not accepted by projector"
What can I do for solve this ?

_Originally posted by @AlainCx in https://github.com/bitfocus/companion-module-generic-pjlink/issues/5#issuecomment-1373631049_

**Comment by istnv** [comment]
The web interface and the PJLink interface do not always have the same password. You may need to configure PJLink access (and password) at the projector first.
