### ISSUE TITLE
Optima Projector Power control

### ISSUE THREAD

**Issue by petenewk** [bitfocus/companion-module-pjlink#52]
I tried adding this to control my Optima WXGA projectors that use PJLink to control the power. They power on and off using PJLink test software from their website with no authentication. When I add the PJLink plug-in to Bitfocus companion, under connections, the projectors show OK, but the projectors do not show up in Presets, only in Variables, and all the values show undefined. 
If I create a general button and choose change power state, nothing happens when I press it.
I tried setting to the wrong IP address and I get an error, so it is communicating. Nothing shows up in the logs at the top of companion.

**Comment by ethan-tripp** [comment]
Hello - I'm also having issues controlling my Optoma projectors via PJLINK. Been using the PJLINK module for years, but when I updated to Companion 2.4.1, control issues started popping up. One of my two projectors keeps erroring out on the companion connections page, but I can still log into the projector using the Optoma web interface. None of the commands seem to function for the projector that shows an "OK" connection on Companion. However, if I disable the connection, run a command (i.e. Video/Audio Mute), it will work once, but require me to disable then enable the connection for another command to work.

**Comment by istnv** [comment]
There have been several recent updates that cover these issues. Feel free to re-open if this is still a problem.

**Comment by ethan-tripp** [comment]
@istnv - are the updates you're referring to in the latest stable build 2.4.2 or beta builds?

**Comment by istnv** [comment]
There were a several issues corrected when the module was refactored for the v3.0 beta
Those were not back-ported to 2.4.2.
