### ISSUE TITLE
Shutter Control Panasonic PT-VMZ51

### ISSUE THREAD

**Issue by bwstunnenberg** [bitfocus/companion-module-pjlink#57]
I'm trying to setup the shutter control of my projector via Companion, but using the Video Mute option in PJLink my projector keeps returning the following error: "Projector reported %1AVMT: Out of parameter".

I found this in the manual:
![image](https://user-images.githubusercontent.com/43135696/228576684-67590fcf-c363-4fbf-b578-7544da646a87.png)

Am I missing something? Thanks in advance!

**Comment by istnv** [comment]
Which version of companion?

**Comment by bwstunnenberg** [comment]
2.4.2!

**Comment by istnv** [comment]
Some projectors will allow you to mute/shutter Video, and leave the audio on. That is a '11' command that your projector does not support.
The A/V mute should work.

**Comment by bwstunnenberg** [comment]
Yes, thank you, that works!
