### ISSUE TITLE
VPL-PHZ60 Variables

### ISSUE THREAD

**Issue by bcsanford** [bitfocus/companion-module-pjlink#66]
Buttons work but the only Variable that populates is the Projector Power Status. 
i would appreciate it if someone could first tell me what information is needed to troubleshoot this.
far as i can tell the driver is behaving as if this is a class 1 projector but this maybe a result of the lack of variables populating.

**Comment by istnv** [comment]
What variables are you expecting to see? 
Some projectors do not send a response for every variable requested.
What does the `class` variable show?

**Comment by bcsanford** [comment]
Hoping for the Mute State variable to work

![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/185097/1e6d034c-d094-4e98-a713-fea20bc50564)


Undefined

![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/185097/639b67a2-2370-4095-9472-8940e6ded8d2)

**Comment by istnv** [comment]
Which version of Companion? That looks like an older version. A lot of changes were added to v3.0 that won't be added to the older v2 release.
Depending on network traffic and the projector CPU speed, it can take up to 30 seconds for variables to be filled.

**Comment by bcsanford** [comment]
2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)

i will update and see if that changes things, thank you for your response.

**Comment by istnv** [comment]
re-open if still an issue
