### ISSUE TITLE
Panasonic PT-VZ580 wont accept password

### ISSUE THREAD

**Issue by dali01** [bitfocus/companion-module-pjlink#7]
@haakonnessjoen I've now tested the recent password fix on my Panasonic PT-VZ580, and unfortunately the issue remains.
Since companion doesn't output much debugging info, it's hard to see what happens.
I've tested with a generic pjlink client, and that works fine with my projector.
I did try to uninstall companion before installing the latest version, to make sure that I have the latest version of the pjlink plugin.

**Comment by jmcc94** [comment]
Is this issue still valid?
