### ISSUE TITLE
Connectivity issue with VPL-FHZ700L

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-pjlink#70]
Recently upgraded from Companion v2.3.1 running on a Pi, to v[3.0.0 (3.0.0+6049-stable-126f27e8)] running on Windows 11. Prior to the upgrade I had no trouble connecting to my projector.
After the upgrade, if the module is disabled/enabled or Companion is closed and then reopened, my projector shows as "disconnected" where it will remain until I turn off and on (sometimes more than once) the PJLink listening service in the projector. After that it remains stable until the next time the module is disabled or Companion shuts down.

The above was all with the pjlink service NOT requiring a password. After I turned on the password, the connectivity became much more reliable. Possibly even perfect (I haven't seen it fail in at least 10 consecutive tries.)

**Comment by mark-epstein** [comment]
I spoke too soon. The projector is staying connected, except for a blip about once a minute
`error: Projector Disconnected
debug: Disconnected
info: Connected`
But none of my control seems to be working now

**Comment by istnv** [comment]
There was another protocol update for companion v3.0.1.
Please try that version. Comment back if there is still a connection problem.

**Comment by mark-epstein** [comment]
I'd say that v3.0.1 might be different, but not better.
Upon Companion restart in 3.0.1 I again found the module offline. I did find, however, that I could correct the connection by turning pjlink authentication (in the projector) on and then off.

**Comment by istnv** [comment]
Can you open the debug log ('>_') and see if anything is generated when it disconnects?

**Comment by mark-epstein** [comment]
This is what it said (this time?) for a disable. Not much.
```
debug: Destroy HMz8cWFIqup4A9xtBzsKh
system: ** Connection stopped **
```

This is for the enable:
```
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\generic-pjlink\main.js" **
system: ** Connection started **
Starting up module class: _
Sentry disabled
Module-host accepted registration
info: Connected
error: Projector Disconnected
debug: Disconnected
info: Connected
error: Projector Disconnected
debug: Disconnected
info: Connected
error: Projector Disconnected
debug: Disconnected
info: Connected
error: Projector Disconnected
debug: Disconnected
info: Connected
error: Projector Disconnected
debug: Disconnected
(etc. seemingly forever)
```

If I then turn on "Requires Authentication" in the pjlink settings of the projector, I immediately get:
```
info: Connected
```
followed after a while by this every 30 seconds:
```
error: Projector Disconnected
debug: Disconnected
info: Connected
```
and in that state none of the module variables updates from "undefined," etc. and my attempts to control have no result.

Lastly if I turn off "Requires Authentication" I get this in the log:
```
info: Connected
debug: Projector does not need password
warn: Projector Busy/Offline
debug: PJLINK ERROR: Projector Busy/Offline
debug: PJLINK ERROR: Projector Busy/Offline
```
All the variables updated to what seem like correct values, and control seems functional.
I don't know when those "Busy/Offline" messages came in. I watched for another 10 minutes or so, didn't happen again.

**Comment by istnv** [comment]
I have noticed that projectors will return 'busy' when they are first turned on (warming up).
Do you have other devices that control the projector? Some units only allow one connection and basically 'abort' anything else. If companion is waiting for a response, it won't get one (or a proper one).

**Comment by mark-epstein** [comment]
Well, I did have a Companion Pi instance running, and it's still online but I deleted the projector module instance from it entirely.

It seems timing related. If I disable and re-enable really quickly it seems to usually work. if I do it slowly, I think sometimes it connects but usually it doesn't. Note: my data is just my recollection, I haven't been keeping actual records

**Comment by mark-epstein** [comment]
...and yes, I'm pretty sure this projector will only accept connections from one client at a time

**Comment by istnv** [comment]
Try adjusting the poll timing. I use 5 seconds for most of my testing.

**Comment by mark-epstein** [comment]
I changed it from 10 (default?) to 5. It seems like it made it slightly
less likely to fail but it still does

**Comment by istnv** [comment]
Do you have a custom module directory set up? I may be able to build a module with more debugging exposed.

**Comment by mark-epstein** [comment]
I do not. I'm willing to do whatever, but I don't know how to do that.

**Comment by istnv** [comment]
I'm trying to create a custom module you could test, but the node package system is down at the moment.
Quickest may be to set up a VPN so I could connect directly to your projector while debugging the module.

**Comment by mark-epstein** [comment]
Sorry it was late. I could probably set up VPN or similar but I don't have that set up at the moment. Let me look into it and I'll get back to you

**Comment by istnv** [comment]
Thanks for your help. Should be in the beta release sometime today
