### ISSUE TITLE
Feature request: Change module connect procedure regarding password 

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-pjlink#74]
Currently the module (tested on 2.1.4) will not connect if the module is configured for a password, even if the pjlink device does not require one.

If the projector/display transmits `PJLINK 0\r` no password is required; the module should communicate even if a password is provided in the module configuration.
If the projector/display transmits `PJLINK 1 XXXXXXXX\r` (where `XXXXXXXX` is a random sequence of characters, the module should try to encrypt its messages with the configured password as it does currently.

Use case: this allows a Companion user to turn off the password requirement in the projector/display without changing anything in Companion. One less variable when trying to troubleshoot connection issues.

**Comment by istnv** [comment]
reopen if still in issue
