### ISSUE TITLE
Unknown Stopped

### ISSUE THREAD

**Issue by EPstudios** [bitfocus/companion-module-pjlink#75]
Hi, 

Im currently getting the "Unknown Stopped" error intermittently on this module. Any idea what might be causing it? Or any advice to try? 

Trying to get logs from the modules itself (have 3 instances running) but keep missing it.

Im on 3.0.1 (3.0.1+6068-stable-a05a9c89)

Companion log attached.

[GIG17E_companion_log_20230918-1637.csv.zip](https://github.com/bitfocus/companion-module-generic-pjlink/files/12650243/GIG17E_companion_log_20230918-1637.csv.zip)

**Comment by istnv** [comment]
This error suggests that the projector is off (hard switch, not standby):
`Network connect EHOSTUNREACH 192.168.1.201:4352`

Have you tried the beta (3.1) Companion release?

**Comment by EPstudios** [comment]
Hi John, thanks for the quick reply. 

Projectors have power (switching the module on and off resolves the issue)

As its intermittent and seems to be happening on multiple machines it might be a network or hardware issue :/ 

Projectors are Epson EB-L630SU

Havent tried the beta, will give it a shot.

**Comment by ldhall1856** [comment]
I also have a Epson projector And am experiencing the same issue. 

I have 3 instances going too! The other 2 are NEC projectors are working properly.

The epson however, will only work if you restart the whole companion application. And it will only work for less than 24 hours.

I can use the IP address of the projector to control it. so I know it isn't the projector. And I know it worked on 2.4.2 of companion.

**Comment by istnv** [comment]
@ldhall1856 Companion 3.0 was a big rewrite. There have been issues cleared up in the beta (3.1) release. Some of the 'errors' and 'warnings'  shown in companion do not affect how the module works.

**Comment by ldhall1856** [comment]
That's good to hear! 

I wish I could use it but currently there are other modules that aren't working with the current beta(tested today).

Thank y'all for all of your hard work!

**Comment by istnv** [comment]
Which modules are you having trouble with?

**Comment by ldhall1856** [comment]
Home assistant

**Comment by istnv** [comment]
Darn. Not one of mine.
