### ISSUE TITLE
Cannot change settings unless connected

### ISSUE THREAD

**Issue by cmtk** [bitfocus/companion-module-pjlink#79]
**Overview:**  The connection settings only load if the device is in a connected state.

After adding a pjlink connection in Companion, if the connection is not successful, the settings can no longer be modified since a "Waiting for connection to start..." message is constantly shown in the Edit connection tab.

This also occurs, for example, if a previously successful connection becomes disconnected (eg: pjlink device password or IP changes).

The connection must then be deleted and recreated to modify settings.

<img width="485" alt="image" src="https://github.com/bitfocus/companion-module-generic-pjlink/assets/12386329/15569493-c7b4-4c8d-ad94-5bcd56744a9e">

Companion 3.2.2

**Comment by istnv** [comment]
Which OS? 
The settings tab should be re-enabled 5-10 seconds after a network failure.

**Comment by cmtk** [comment]
Linux (x64). Happy to test anything specific if needed.

Settings tab does appear to reload (flash) roughly every 5-10 seconds, but always with the Waiting message.

**Comment by istnv** [comment]
That reload cycle only happens with the wrong passcode. 
The module logic does not handle that well (at all) and keeps re-trying without allowing the configuration time to update.
Network errors leave enough time for the configuration tab to process. 
I'll need to refactor the communication sequence to account for the wrong passcode.
No time for a few days, though. Sorry.
