### ISSUE TITLE
Warning Command for different Protocol Class: %2RLMP Epson EB-L530U

### ISSUE THREAD

**Issue by AlexWHughes** [bitfocus/companion-module-pjlink#84]
Using 8 Epson EB-L530U projectors for just lamp on/off commands we get the following error after every device poll. Device is functional but just fills the log with "Warning Command for different Protocol Class: %2RLMP" errors. 

It would be good to have the option to disable polling as I think Epson are just not complying with the standard. 

Companion version 3.2.2 
JBMIA: Projector; PJLink v2.2.0

**Comment by istnv** [comment]
That would also disable ALL of the other variables and feedback options.
Have you tried the recent 3.3 release of Companion?
There have been several updates to this module that are better at avoiding log spam.
Many models do not implement the complete protocol and whine about something they didn't/forgot to account for.
If it is still an issue, let me know and I'll work in some way to limit the amount of warnings.

**Comment by AlexWHughes** [comment]
I haven't tested 3.3 as I know it changes a few things and we are week 1 of a 3 week show. If its better 3.3 you can close this and I apologize for wasting your time.

**Comment by istnv** [comment]
No problem. Re-open this issue when you get a chance to test if the stable 3.3 release still spams the log.
