### ISSUE TITLE
warning message - %1L: Out of parameter

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion-module-pjlink#87]
We have 10 projectors, and one of the projectors started showing this message (screencapture). Couldn't find what %1L might mean. We are on version 3.0.1, will it help to update to the latest version? Is 3.3.1 stable?

![image](https://github.com/user-attachments/assets/c4c0a1a6-d9d1-48a1-97ff-8434c4685046)

**Comment by istnv** [comment]
That error happens on some Laser projectors when queried about 'Lamp hours'. 
There have been several updates since 3.0.1.
Try a newer release. Certain 'errors' are filtered and no longer spam the log.
