### ISSUE TITLE
Panasonic PT-MZ670 Compatability

### ISSUE THREAD

**Issue by rtdean** [bitfocus/companion-module-pjlink#91]
It looks like the PJLink module is almost exactly what I'm looking for to control a Panasonic PT-MZ670 projector.  However, the projector is... just different enough that I'm not able to authenticate.

When you connect to the PJLink port on the Panasonic, it's welcome banner is `NTCONTROL <mode> <random number seed>\r` instead of `PJLINK <mode>...\r`, and that the MD5'd response format is different, being `<username>:<password>:<random number seed>`.

As I'm new to the bitfocus/companion ecosystem, is the correct path forward here to fork the module and make a `companion-module-panasonic-pjlink` with the Panasonic differences?

At least in the PT-MZ670 manual, the PJLink protocol documentation is in Chapter 7, curiously named the "Appendix", on pages 210-213.

**Comment by istnv** [comment]
You set the password with the IR remote control or the web page.
Enter the IP and password into the PJLink configuration. The password is the same as the web password.
They have another LAN control protocol (not PJLink) which starts with the `NTCONTROL...` text. 
The manual is confusing.

**Comment by rtdean** [comment]
Well, that's... Frustrating. Oh well.  Sorry for the noise.
